---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[et_www::default]
    attributes:
      newrelic:
        server_monitor_agent:
          service_notify_action: nothing
          service_actions:
            - enable
      newrelic_meetme_plugin:
        service_notify_action: nothing
        service_actions:
          - enable
