---
driver:
  name: vagrant
  customize:
    cpus: 4
    memory: 1536

provisioner:
  name: chef_zero
  data_bags_path: <%= ENV['CHEF_REPO'] %>/data_bags
  encrypted_data_bag_secret_key_path: <%= ENV['HOME'] %>/.chef/encrypted_data_bag_secret

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[et_www::default]
    attributes:
      newrelic:
        license: TESTKEY_PHP_AGENT
        server_monitor_agent:
          service_notify_action: nothing
          service_actions:
            - enable
      newrelic_meetme_plugin:
        license: TESTKEY_PLUGIN_AGENT
        service_notify_action: nothing
        service_actions:
          - enable
